### ISSUE TITLE
question about UART Debug tool for X88proX3

### ISSUE THREAD

**Issue by araczkowski** [Raxone/amlogic-usbdl_s905x3#2]
I'm trying to check the boot logs on the device, I'm using CuteCom for this

![image](https://github.com/Raxone/amlogic-usbdl_s905x3/assets/1263968/1d32a974-ea01-4dd8-a386-bfd6d99e5f06)

I checked different connection settings but there are no data on /dev/ttyUSB0

on your video I saw that it works for you
![image](https://github.com/Raxone/amlogic-usbdl_s905x3/assets/1263968/14495368-3d44-42e7-ba3d-fed233edc90c)

what program are you using? do I have to do something special to see the logs? It works fine for my other boxes but not for X88proX3

![image](https://github.com/Raxone/amlogic-usbdl_s905x3/assets/1263968/7d88d467-8a5e-4300-a75b-bf4872629671)

I'm wondering that maybe something is physically missing on my board...

**Comment by Raxone** [comment]
In picture i don't see where you connect uart.
I use picocom but that is not important  baudrate is 115200 not 19200

**Comment by araczkowski** [comment]
I compare my X88proX3 board with the same board picture from the Internet 
and it looks that on my board there is no path from RX TX to SoC - look on the pictures below 

Correct paths - board picture from the Internet:
![image](https://github.com/Raxone/amlogic-usbdl_s905x3/assets/1263968/7649e292-00d9-4490-8aae-f34deb3bb9cf)

My board - no paths from RX TX pins to SoC:
![image](https://github.com/Raxone/amlogic-usbdl_s905x3/assets/1263968/949e2237-ea96-497d-a137-60798b677957)


Do you know  (can you check via electronic meter) if these RX TX pins are going straight to the SoC S905x3 pins ,or maybe there are some other places on the board where I can connect to RX TX?

**Comment by Raxone** [comment]
2 places for uart is,  from (bl1) and sdcard/to uart(bl2).
If uart is ok connected to cpu it must have some voltage on tx/rx.
In my case rx 0.5v and tx 3.3v when it is board powered.
When board power off the test with diode mode voltage drop in my case is
1.000 for tx and rx.

**Comment by araczkowski** [comment]
thanks @Raxone for the answer it was very helpful, I tried but unfortunately I was not able to connect and debug the boot
anyway I will close this, because I do not have any idea how to make this work
